openapi: 3.0.3
info:
  title: 국내 전자공시 시스템 DART(Data Analysis, Retrieval and Transfer System)
  description: 국내 상장기업의 전자공시 정보를 제공하는 API 서비스입니다.
  version: 1.0.0
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  contact:
    name: 강한구
    email: kgcrom@hotmail.com
servers:
  - url: https://opendart.fss.or.kr
    description: DART server
tags:
  - name: CorporateDisclosure
    description: 공시정보
  - name: RegularDisclosureKey
    description: 정기보고서 주요정보
  - name: RegularDisclosureFinancialStatement
    description: 정기보고서 재무정보
  - name: ShareDisclosure
    description: 지분공시 종합정보
  - name: IrregularDisclosureKey
    description: 주요사항보고서 주요정보
paths:
  /api/list.json:
    get:
      operationId: getCorporateList
      summary: 공시검색
      description: |
        공시 유형별, 회사별, 날짜별 등 여러가지 조건으로 공시보고서 검색기능을 제공합니다.
      tags:
        - CorporateDisclosure
      parameters:
        - in: query
          name: bgn_de
          description: |
            시작일

            검색시작 접수일자(YYYYMMDD)<br/>
            1) 기본값 : 종료일(end_de)<br/>
            2) 고유번호(corp_code)가 없는 경우 검색기간은 3개월로 제한
          required: false
          schema:
            type: string
            example: '20240601'
            maxLength: 8
        - in: query
          name: end_de
          description: |
            종료일

            검색종료 접수일자(YYYYMMDD)
            1) 기본값 : 당일
          required: false
          schema:
            type: string
            example: '20240601'
            maxLength: 8
        - in: query
          name: corp_code
          description: |
            고유번호

            공시대상회사의 고유번호(8자리)
          required: false
          schema:
            type: string
            example: '005930'
            maxLength: 8
        - in: query
          name: last_reprt_at
          description: |
            최종보고서 검색여부

            최종보고서만 검색여부(Y or N)
            1) 기본값 : N(정정이 있는 경우 최종정정만 검색)
          required: true
          schema:
            type: string
            enum:
              - 'Y'
              - 'N'
            default: 'N'
            example: 'Y'
        - in: query
          name: pblntf_ty
          description: |
            공시유형

            A : 정기공시<br/>
            B : 주요사항보고<br/>
            C : 발행공시<br/>
            D : 지분공시<br/>
            E : 기타공시<br/>
            F : 외부감사관련<br/>
            G : 펀드공시<br/>
            H : 자산유동화<br/>
            I : 거래소공시<br/>
            J : 공정위공시
          required: false
          schema:
            type: string
            enum:
              - A
              - B
              - C
              - D
              - E
              - F
              - G
              - H
              - I
              - J
            example: A
        - in: query
          name: pblntf_detail_ty
          description: |
            공시상세유형

            - A001 : 사업보고서<br/>
            - A002 : 반기보고서<br/>
            - A003 : 분기보고서<br/>
            - A004 : 등록법인결산서류(자본시장법이전)<br/>
            - A005 : 소액공모법인결산서류<br/>
            - B001 : 주요사항보고서<br/>
            - B002 : 주요경영사항신고(자본시장법 이전)<br/>
            - B003 : 최대주주등과의거래신고(자본시장법 이전)<br/>
            - C001 : 증권신고(지분증권)<br/>
            - C002 : 증권신고(채무증권)<br/>
            - C003 : 증권신고(파생결합증권)<br/>
            - C004 : 증권신고(합병등)<br/>
            - C005 : 증권신고(기타)<br/>
            - C006 : 소액공모(지분증권)<br/>
            - C007 : 소액공모(채무증권)<br/>
            - C008 : 소액공모(파생결합증권)<br/>
            - C009 : 소액공모(합병등)<br/>
            - C010 : 소액공모(기타)<br/>
            - C011 : 호가중개시스템을통한소액매출<br/>
            - D001 : 주식등의대량보유상황보고서<br/>
            - D002 : 임원ㆍ주요주주특정증권등소유상황보고서<br/>
            - D003 : 의결권대리행사권유<br/>
            - D004 : 공개매수<br/>
            - E001 : 자기주식취득/처분<br/>
            - E002 : 신탁계약체결/해지<br/>
            - E003 : 합병등종료보고서<br/>
            - E004 : 주식매수선택권부여에관한신고<br/>
            - E005 : 사외이사에관한신고<br/>
            - E006 : 주주총회소집보고서<br/>
            - E007 : 시장조성/안정조작<br/>
            - E008 : 합병등신고서(자본시장법 이전)<br/>
            - E009 : 금융위등록/취소(자본시장법 이전)<br/>
            - F001 : 감사보고서<br/>
            - F002 : 연결감사보고서<br/>
            - F003 : 결합감사보고서<br/>
            - F004 : 회계법인사업보고서<br/>
            - F005 : 감사전재무제표미제출신고서<br/>
            - G001 : 증권신고(집합투자증권-신탁형)<br/>
            - G002 : 증권신고(집합투자증권-회사형)<br/>
            - G003 : 증권신고(집합투자증권-합병)<br/>
            - H001 : 자산유동화계획/양도등록<br/>
            - H002 : 사업/반기/분기보고서<br/>
            - H003 : 증권신고(유동화증권등)<br/>
            - H004 : 채권유동화계획/양도등록<br/>
            - H005 : 자산유동화관련중요사항발생등보고<br/>
            - H006 : 주요사항보고서<br/>
            - I001 : 수시공시<br/>
            - I002 : 공정공시<br/>
            - I003 : 시장조치/안내<br/>
            - I004 : 지분공시<br/>
            - I005 : 증권투자회사<br/>
            - I006 : 채권공시<br/>
            - J001 : 대규모내부거래관련<br/>
            - J002 : 대규모내부거래관련(구)<br/>
            - J004 : 기업집단현황공시<br/>
            - J005 : 비상장회사중요사항공시<br/>
            - J006 : 기타공정위공시<br/>
            - J008 : 대규모내부거래관련(공익법인용)<br/>
            - J009 : 하도급대금결제조건공시
          required: false
          schema:
            type: string
            enum:
              - A001
              - A002
              - A003
              - A004
              - A005
              - B001
              - B002
              - B003
              - C001
              - C002
              - C003
              - C004
              - C005
              - C006
              - C007
              - C008
              - C009
              - C010
              - C011
              - D001
              - D002
              - D003
              - D004
              - E001
              - E002
              - E003
              - E004
              - E005
              - E006
              - E007
              - E008
              - E009
              - F001
              - F002
              - F003
              - F004
              - F005
              - G001
              - G002
              - G003
              - H001
              - H002
              - H003
              - H004
              - H005
              - H006
              - I001
              - I002
              - I003
              - I004
              - I005
              - I006
              - J001
              - J002
              - J004
              - J005
              - J006
              - J008
              - J009
            example: A001
        - in: query
          name: corp_cls
          description: |
            법인구분

            - Y : 유가증권시장<br/>
            - K : 코스닥<br/>
            - N : 코넥스<br/>
            - E : 기타<br/>
            ※ 없으면 전체조회, 복수조건 불가
          required: false
          schema:
            type: string
            enum:
              - 'Y'
              - K
              - 'N'
              - E
            example: 'Y'
        - in: query
          name: sort
          description: |
            정렬

            - date : 접수일자<br/>
            - crp : 회사명<br/>
            - rpt : 보고서명<br/>
            ※ 기본값 : date
          required: false
          schema:
            type: string
            enum:
              - date
              - crp
              - rpt
            default: date
            example: crp
        - in: query
          name: sort_mth
          description: |
            정렬방법

            - asc : 오름차순<br/>
            - desc : 내림차순<br/>
            ※ 기본값 : desc
          required: false
          schema:
            type: string
            enum:
              - asc
              - desc
            default: desc
            example: asc
        - in: query
          name: page_no
          description: |
            페이지 번호(1~n)<br/>
            ※ 기본값 : 1
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
            example: 3
        - in: query
          name: page_count
          description: |
            페이지 별 건수(1~100)<br/>
            ※ 기본값 : 10<br/>
            ※ 최대값 : 100
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 999
            default: 10
            example: 33
      responses:
        '200':
          $ref: '#/components/responses/list'
  /api/company.json:
    get:
      operationId: getCorporateCompany
      summary: 기업개황
      description: |
        DART에 등록되어있는 기업의 개황정보를 제공합니다.
      tags:
        - CorporateDisclosure
      parameters:
        - in: query
          name: corp_code
          description: |
            고유번호

            공시대상회사의 고유번호(8자리)
          required: true
          schema:
            type: string
            example: '005930'
            maxLength: 8
      responses:
        '200':
          $ref: '#/components/responses/company'
  /api/document.xml:
    get:
      operationId: getCorporateDocument
      summary: 공시서류원본파일
      description: |
        공시보고서 원본파일을 제공합니다.
      tags:
        - CorporateDisclosure
      parameters:
        - in: query
          name: rcept_no
          description: 접수번호
          required: true
          schema:
            type: string
            example: '20240516001421'
            maxLength: 14
      responses:
        '200':
          description: 공시서류원본파일 조회 성공
          content:
            application/zip:
              schema:
                type: string
                format: binary
  /api/corpCode.xml:
    get:
      operationId: getCorporateCode
      summary: 고유번호
      description: |
        DART에 등록되어있는 공시대상회사의 고유번호,회사명,종목코드, 최근변경일자를 파일로 제공합니다.
      tags:
        - CorporateDisclosure
      responses:
        '200':
          description: 고유번호 조회 성공
          content:
            application/zip:
              schema:
                type: string
                format: binary
components:
  securitySchemes:
    authKey:
      type: apiKey
      in: header
      name: crtfc_key
      description: |
        DART OpenAPI 인증키

        redoc lint, autorest에서 인증은 필수여서 추가함
  schemas:
    status:
      description: |
        에러 및 정보코드

        000 :정상
        010 :등록되지 않은 키입니다.
        011 :사용할 수 없는 키입니다. 오픈API에 등록되었으나, 일시적으로 사용 중지된 키를 통하여 검색하는 경우 발생합니다.
        012 :접근할 수 없는 IP입니다.
        013 :조회된 데이타가 없습니다.
        014 :파일이 존재하지 않습니다.
        020 :요청 제한을 초과하였습니다.
        적으로는 20,000건 이상의 요청에 대하여 이 에러 메시지가 발생되나, 요청 제한이 다르게 설정된 경우에는 이에 준하여 발생됩니다.
        021 :조회 가능한 회사 개수가 초과하였습니다.(최대 100건)
        100 :필드의 부적절한 값입니다. 필드 설명에 없는 값을 사용한 경우에 발생하는 메시지입니다.
        101 :부적절한 접근입니다.
        800 :시스템 점검으로 인한 서비스가 중지 중입니다.
        900 :정의되지 않은 오류가 발생하였습니다.
        901 :사용자 계정의 개인정보 보유기간이 만료되어 사용할 수 없는 키입니다. 관리자 이메일(opendart@fss.or.kr)로 문의하시기 바랍니다.
      type: string
      enum:
        - '000'
        - '010'
        - '011'
        - '012'
        - '013'
        - '014'
        - '020'
        - '021'
        - '100'
        - '101'
        - '800'
        - '900'
        - '901'
      example: '000'
  responses:
    list:
      description: 공시검색 조회 성공
      content:
        application/json:
          schema:
            type: object
            properties:
              result:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/status'
                  message:
                    type: string
                    description: 에러 및 정보 메시지
                    example: 정상
                  page_no:
                    type: integer
                    description: 페이지 번호
                    example: 1
                  page_count:
                    type: integer
                    description: 페이지 별 건수
                    example: 10
                  total_count:
                    type: integer
                    description: 총 건수
                    example: 100
                  total_page:
                    type: integer
                    description: 총 페이지 수
                    example: 10
                  list:
                    type: array
                    items:
                      type: object
                      properties:
                        corp_cls:
                          type: string
                          description: |
                            법인구분

                            - Y : 유가증권시장<br/>
                            - K : 코스닥<br/>
                            - N : 코넥스<br/>
                            - E : 기타<br/>
                          example: 'Y'
                        corp_name:
                          type: string
                          description: |
                            종목명(법인명)<br/>
                            공시대상회사의 종목명(상장사) 또는 법인명(기타법인)
                          example: 삼성전자
                        corp_code:
                          type: string
                          description: 공시대상회사의 고유번호(8자리)
                          example: '005930'
                          maxLength: 8
                        stock_code:
                          type: string
                          description: 상장회사의 종목코드(6자리)
                          example: '005930'
                          maxLength: 6
                        report_nm:
                          type: string
                          description: |
                            보고서명

                            공시구분+보고서명+기타정보<br/>
                            [기재정정] : 본 보고서명으로 이미 제출된 보고서의 기재내용이 변경되어 제출된 것임<br/>
                            [첨부정정] : 본 보고서명으로 이미 제출된 보고서의 첨부내용이 변경되어 제출된 것임<br/>
                            [첨부추가] : 본 보고서명으로 이미 제출된 보고서의 첨부서류가 추가되어 제출된 것임<br/>
                            [변경등록] : 본 보고서명으로 이미 제출된 보고서의 유동화계획이 변경되어 제출된 것임<br/>
                            [연장결정] : 본 보고서명으로 이미 제출된 보고서의 신탁계약이 연장되어 제출된 것임<br/>
                            [발행조건확정] : 본 보고서명으로 이미 제출된 보고서의 유가증권 발행조건이 확정되어 제출된 것임<br/>
                            [정정명령부과] : 본 보고서에 대하여 금융감독원이 정정명령을 부과한 것임<br/>
                            [정정제출요구] : 본 보고서에 대하여 금융감독원이 정정제출요구을 부과한 것임
                          example: '[기재정정]단일판매ㆍ공급계약체결'
                        rcept_no:
                          type: string
                          description: |
                            접수번호(14자리)

                            ※ 공시뷰어 연결에 이용예시<br/>
                            - PC용 : https://dart.fss.or.kr/dsaf001/main.do?rcpNo=접수번호
                          example: '20220401000001'
                        flr_nm:
                          type: string
                          description: 공시 제출인명
                          example: 홍길동
                        rcept_dt:
                          type: string
                          description: 공시 접수일자(YYYYMMDD)
                          example: '20220401'
                        rm:
                          type: string
                          description: |
                            비고

                            조합된 문자로 각각은 아래와 같은 의미가 있음<br/>
                            - 유 : 본 공시사항은 한국거래소 유가증권시장본부 소관임<br/>
                            - 코 : 본 공시사항은 한국거래소 코스닥시장본부 소관임<br/>
                            - 채 : 본 문서는 한국거래소 채권상장법인 공시사항임<br/>
                            - 넥 : 본 문서는 한국거래소 코넥스시장 소관임<br/>
                            - 공 : 본 공시사항은 공정거래위원회 소관임<br/>
                            - 연 : 본 보고서는 연결부분을 포함한 것임<br/>
                            - 정 : 본 보고서 제출 후 정정신고가 있으니 관련 보고서를 참조하시기 바람<br/>
                            - 철 : 본 보고서는 철회(간주)되었으니 관련 철회신고서(철회간주안내)를 참고하시기 바람
                          example: 유
                          maxLength: 1
    company:
      description: 기업개황 조회 성공
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                $ref: '#/components/schemas/status'
              message:
                type: string
                description: 에러 및 정보 메시지
                example: 정상
              corp_name:
                type: string
                description: 정식명칭
                example: 삼성전자(주)
              corp_name_eng:
                type: string
                description: 영문명칭
                example: Samsung Electronics Co., Ltd.
              stock_name:
                type: string
                description: 종목명(상장사) 또는 약식명칭(기타법인)
                example: 삼성전자
              stock_code:
                type: string
                description: 상장회사인 경우 주식의 종목코드
                example: '005930'
                maxLength: 6
              ceo_nm:
                type: string
                description: 대표자명
                example: 한종희
              corp_cls:
                type: string
                description: 법인구분
                enum:
                  - 'Y'
                  - 'N'
                example: 'Y'
              jurir_no:
                type: string
                description: 법인등록번호
                example: '1301110006246'
              bizr_no:
                type: string
                description: 사업자등록번호
                example: '1248100998'
              adres:
                type: string
                description: 주소
                example: 경기도 수원시 영통구  삼성로 129 (매탄동)
              hm_url:
                type: string
                description: 홈페이지
                example: www.samsung.com/sec
              ir_url:
                type: string
                description: IR홈페이지
                example: ''
              phn_no:
                type: string
                description: 전화번호
                example: 02-2255-0114
              fax_no:
                type: string
                description: 팩스번호
                example: 031-200-7538
              induty_code:
                type: string
                description: 업종코드
                example: '264'
              est_dt:
                type: string
                description: 설립일(YYYYMMDD)
                example: '19690113'
              acc_mt:
                type: string
                description: 결산월(MM)
                example: '12'
