openapi: 3.0.3
info:
  title: 한국투자증권 개발자센터 KIS Developers
  description: OpenKIS API Service
  version: 1.0.0
servers:
  - url: 'https://openapi.koreainvestment.com:9443'
    description: KIS Production server
  - url: 'https://openapivts.koreainvestment.com:29443'
    description: KIS Sandbox server
tags:
  - name: DomesticStock
    description: 국내주식
  - name: Quatations
    description: 시세

paths:
  /oauth2/tokenP:
    post:
      operationId: getAccessToken
      summary: Get Access Token
      description: |
        # Access Token 발급
        본인 계좌에 필요한 인증 절차로, 인증을 통해 접근 토큰을 부여받아 오픈API 활용이 가능합니다.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                  description: 인증방식 (client_credentials 고정)
                  example: client_credentials
                appkey:
                  type: string
                  description: 한국투자증권 홈페이지에서 발급받은 appkey (절대 노출되지 않도록 주의해주세요.)
                  example: PSg5dctL9dKPo727J13Ur405OSXXXXXXXXXX
                appsecret:
                  type: string
                  description: 한국투자증권 홈페이지에서 발급받은 appsecret (절대 노출되지 않도록 주의해주세요.)
                  example: o2t8zS68zpdjGuWvFyM9VikjXE0i0CbgPEamnqPA00G0bIfrdfQb2RUD1xP7SqatQXr1cD1fGUNsb78MMXoq6o4lAYt9YTtHAjbMoFy+c72kbq5owQY1Pvp39/x6ejpJlXCj7gE3yVOB/h25Hvl+URmYeBTfrQeOqIAOYc/OIXXXXXXXXXX
              required:
                - grant_type
                - appkey
                - appsecret
      responses:
        '200':
          description: Access Token 발급 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: |
                      OAuth 토큰이 필요한 API 경우 발급한 Access token
                      ex) "eyJ0eXUxMiJ9.eyJz…..................................."
                      
                      - 일반개인고객/일반법인고객
                      . Access token 유효기간 1일
                      .. 일정시간(6시간) 이내에 재호출 시에는 직전 토큰값을 리턴
                      . OAuth 2.0의 Client Credentials Grant 절차를 준용
                      
                      - 제휴법인
                      . Access token 유효기간 3개월
                      . Refresh token 유효기간 1년
                      . OAuth 2.0의 Authorization Code Grant 절차를 준용
                  token_type:
                    type: string
                    description: 접근토큰유형 (Bearer 고정)
                    example: Bearer
                  expires_in:
                    type: integer
                    description: Access token 만료시간 (초)
                    example: 7776000
                  access_token_token_expire:
                    type: string
                    format: date-time
                    description: Access token 만료시간 (년:월:일 시:분:초)
                    example: 2022-08-30 08:10:10
