import pytest
import responses

from finance_clue.openkis import OpenKisClient


def test_domestic_stock_price(integration_openkis_client: OpenKisClient):
    """국내주식 현재가 시세 조회 integrated test"""
    resp = integration_openkis_client.get_domestic_stock_price(fid_input_iscd="005930")
    # TODO schema validation  https://github.com/keleshev/schema
    example = {
        "output": {
            "iscd_stat_cls_code": "55",
            "marg_rate": "20.00",
            "rprs_mrkt_kor_name": "KOSPI200",
            "bstp_kor_isnm": "전기.전자",
            "temp_stop_yn": "N",
            "oprc_rang_cont_yn": "N",
            "clpr_rang_cont_yn": "N",
            "crdt_able_yn": "Y",
            "grmn_rate_cls_code": "40",
            "elw_pblc_yn": "Y",
            "stck_prpr": "75700",
            "prdy_vrss": "-1600",
            "prdy_vrss_sign": "5",
            "prdy_ctrt": "-2.07",
            "acml_tr_pbmn": "1109351578979",
            "acml_vol": "14598755",
            "prdy_vrss_vol_rate": "68.90",
            "stck_oprc": "76100",
            "stck_hgpr": "76600",
            "stck_lwpr": "75600",
            "stck_mxpr": "100400",
            "stck_llam": "54200",
            "stck_sdpr": "77300",
            "wghn_avrg_stck_prc": "75990.12",
            "hts_frgn_ehrt": "55.34",
            "frgn_ntby_qty": "-1784782",
            "pgtr_ntby_qty": "-3070030",
            "pvt_scnd_dmrs_prc": "79166",
            "pvt_frst_dmrs_prc": "78232",
            "pvt_pont_val": "77666",
            "pvt_frst_dmsp_prc": "76732",
            "pvt_scnd_dmsp_prc": "76166",
            "dmrs_val": "77950",
            "dmsp_val": "76450",
            "cpfn": "7780",
            "rstc_wdth_prc": "23100",
            "stck_fcam": "100",
            "stck_sspr": "61840",
            "aspr_unit": "100",
            "hts_deal_qty_unit_val": "1",
            "lstn_stcn": "5969782550",
            "hts_avls": "4519125",
            "per": "35.52",
            "pbr": "1.46",
            "stac_month": "12",
            "vol_tnrt": "0.24",
            "eps": "2131.00",
            "bps": "52002.00",
            "d250_hgpr": "86000",
            "d250_hgpr_date": "20240408",
            "d250_hgpr_vrss_prpr_rate": "-11.98",
            "d250_lwpr": "65800",
            "d250_lwpr_date": "20230818",
            "d250_lwpr_vrss_prpr_rate": "15.05",
            "stck_dryy_hgpr": "86000",
            "dryy_hgpr_vrss_prpr_rate": "-11.98",
            "dryy_hgpr_date": "20240408",
            "stck_dryy_lwpr": "70700",
            "dryy_lwpr_vrss_prpr_rate": "7.07",
            "dryy_lwpr_date": "20240118",
            "w52_hgpr": "86000",
            "w52_hgpr_vrss_prpr_ctrt": "-11.98",
            "w52_hgpr_date": "20240408",
            "w52_lwpr": "65800",
            "w52_lwpr_vrss_prpr_ctrt": "15.05",
            "w52_lwpr_date": "20230818",
            "whol_loan_rmnd_rate": "0.16",
            "ssts_yn": "N",
            "stck_shrn_iscd": "005930",
            "fcam_cnnm": "100",
            "cpfn_cnnm": "7,780 억",
            "frgn_hldn_qty": "3303737099",
            "vi_cls_code": "N",
            "ovtm_vi_cls_code": "N",
            "last_ssts_cntg_qty": "40686",
            "invt_caful_yn": "N",
            "mrkt_warn_cls_code": "00",
            "short_over_yn": "N",
            "sltr_yn": "N",
        },
        "rt_cd": "0",
        "msg_cd": "MCA00000",
        "msg1": "정상처리 되었습니다.",
    }

    assert resp["rt_cd"] == "0"
    assert resp["msg_cd"] == "MCA00000"
    assert resp["output"]["bstp_kor_isnm"] == "전기.전자"


def test_domestic_stock_conclusion(
    integration_openkis_client: OpenKisClient,
):
    """국내주식 현재가 체결조회 integrated test"""
    resp = integration_openkis_client.get_domestic_stock_conclusion(
        fid_input_iscd="005930",
    )

    example = {
        "output": [
            {
                "stck_cntg_hour": "155922",
                "stck_prpr": "75700",
                "prdy_vrss": "-1600",
                "prdy_vrss_sign": "5",
                "cntg_vol": "2",
                "tday_rltv": "74.95",
                "prdy_ctrt": "-2.07",
            },
            {
                "stck_cntg_hour": "155849",
                "stck_prpr": "75700",
                "prdy_vrss": "-1600",
                "prdy_vrss_sign": "5",
                "cntg_vol": "5",
                "tday_rltv": "74.95",
                "prdy_ctrt": "-2.07",
            },
            {
                "stck_cntg_hour": "155830",
                "stck_prpr": "75700",
                "prdy_vrss": "-1600",
                "prdy_vrss_sign": "5",
                "cntg_vol": "2",
                "tday_rltv": "74.95",
                "prdy_ctrt": "-2.07",
            },
            {
                "stck_cntg_hour": "155810",
                "stck_prpr": "75700",
                "prdy_vrss": "-1600",
                "prdy_vrss_sign": "5",
                "cntg_vol": "2",
                "tday_rltv": "74.95",
                "prdy_ctrt": "-2.07",
            },
            {
                "stck_cntg_hour": "155759",
                "stck_prpr": "75700",
                "prdy_vrss": "-1600",
                "prdy_vrss_sign": "5",
                "cntg_vol": "9",
                "tday_rltv": "74.95",
                "prdy_ctrt": "-2.07",
            },
            {
                "stck_cntg_hour": "155745",
                "stck_prpr": "75700",
                "prdy_vrss": "-1600",
                "prdy_vrss_sign": "5",
                "cntg_vol": "1",
                "tday_rltv": "74.95",
                "prdy_ctrt": "-2.07",
            },
            {
                "stck_cntg_hour": "155632",
                "stck_prpr": "75700",
                "prdy_vrss": "-1600",
                "prdy_vrss_sign": "5",
                "cntg_vol": "1",
                "tday_rltv": "74.95",
                "prdy_ctrt": "-2.07",
            },
            {
                "stck_cntg_hour": "155615",
                "stck_prpr": "75700",
                "prdy_vrss": "-1600",
                "prdy_vrss_sign": "5",
                "cntg_vol": "1",
                "tday_rltv": "74.95",
                "prdy_ctrt": "-2.07",
            },
            {
                "stck_cntg_hour": "155536",
                "stck_prpr": "75700",
                "prdy_vrss": "-1600",
                "prdy_vrss_sign": "5",
                "cntg_vol": "90",
                "tday_rltv": "74.95",
                "prdy_ctrt": "-2.07",
            },
            {
                "stck_cntg_hour": "155519",
                "stck_prpr": "75700",
                "prdy_vrss": "-1600",
                "prdy_vrss_sign": "5",
                "cntg_vol": "1",
                "tday_rltv": "74.95",
                "prdy_ctrt": "-2.07",
            },
            {
                "stck_cntg_hour": "155519",
                "stck_prpr": "75700",
                "prdy_vrss": "-1600",
                "prdy_vrss_sign": "5",
                "cntg_vol": "1000",
                "tday_rltv": "74.95",
                "prdy_ctrt": "-2.07",
            },
            {
                "stck_cntg_hour": "155453",
                "stck_prpr": "75700",
                "prdy_vrss": "-1600",
                "prdy_vrss_sign": "5",
                "cntg_vol": "5",
                "tday_rltv": "74.97",
                "prdy_ctrt": "-2.07",
            },
        ],
        "rt_cd": "0",
        "msg_cd": "MCA00000",
        "msg1": "정상처리 되었습니다.",
    }

    assert resp["rt_cd"] == "0"
    assert resp["msg_cd"] == "MCA00000"
    output = resp["output"]
    assert len(output) == 30


def test_domestic_stock_daily_price(
    integration_openkis_client: OpenKisClient,
):
    """국내주식 현재가 일자별 조회 integrated test"""
    resp = integration_openkis_client.get_domestic_stock_daily_price(
        fid_input_iscd="005930",
        fid_period_div_code="W",
        fid_org_adj_prc="1",
    )

    example = {
        "output": [
            {
                "stck_bsop_date": "20240610",
                "stck_oprc": "76100",
                "stck_hgpr": "76600",
                "stck_lwpr": "75600",
                "stck_clpr": "75700",
                "acml_vol": "14598755",
                "prdy_vrss_vol_rate": "-80.32",
                "prdy_vrss": "-1600",
                "prdy_vrss_sign": "5",
                "prdy_ctrt": "-2.07",
                "hts_frgn_ehrt": "55.34",
                "frgn_ntby_qty": "-1784782",
                "flng_cls_code": "00",
                "acml_prtt_rate": "1.00",
            },
            {
                "stck_bsop_date": "20240603",
                "stck_oprc": "74400",
                "stck_hgpr": "78600",
                "stck_lwpr": "74200",
                "stck_clpr": "77300",
                "acml_vol": "74171638",
                "prdy_vrss_vol_rate": "-49.67",
                "prdy_vrss": "3800",
                "prdy_vrss_sign": "2",
                "prdy_ctrt": "5.17",
                "hts_frgn_ehrt": "55.37",
                "frgn_ntby_qty": "3732278",
                "flng_cls_code": "00",
                "acml_prtt_rate": "0.00",
            },
            {
                "stck_bsop_date": "20240527",
                "stck_oprc": "75300",
                "stck_hgpr": "78200",
                "stck_lwpr": "73500",
                "stck_clpr": "73500",
                "acml_vol": "147359198",
                "prdy_vrss_vol_rate": "48.42",
                "prdy_vrss": "-2400",
                "prdy_vrss_sign": "5",
                "prdy_ctrt": "-3.16",
                "hts_frgn_ehrt": "55.31",
                "frgn_ntby_qty": "-28820600",
                "flng_cls_code": "00",
                "acml_prtt_rate": "0.00",
            },
            {
                "stck_bsop_date": "20240520",
                "stck_oprc": "78100",
                "stck_hgpr": "79100",
                "stck_lwpr": "75700",
                "stck_clpr": "75900",
                "acml_vol": "99288237",
                "prdy_vrss_vol_rate": "47.48",
                "prdy_vrss": "-1500",
                "prdy_vrss_sign": "5",
                "prdy_ctrt": "-1.94",
                "hts_frgn_ehrt": "55.79",
                "frgn_ntby_qty": "-6259092",
                "flng_cls_code": "00",
                "acml_prtt_rate": "0.00",
            },
        ],
        "rt_cd": "0",
        "msg_cd": "MCA00000",
        "msg1": "정상처리 되었습니다.",
    }

    assert resp["rt_cd"] == "0"
    assert len(resp["output"]) == 30
    assert all(
        [item["prdy_vrss_sign"] in ("1", "2", "3", "4", "5") for item in resp["output"]]
    )


def test_domestic_stock_quote_and_expected_conclusion(
    integration_openkis_client: OpenKisClient,
):
    """국내주식 현재가 호가/예상체결 조회 integrated test"""
    resp = integration_openkis_client.get_domestic_stock_quote_and_expected_conclusion(
        fid_input_iscd="005930",
    )

    example = {
        "output1": {
            "aspr_acpt_hour": "160000",
            "askp1": "75800",
            "askp2": "75900",
            "askp3": "76000",
            "askp4": "76100",
            "askp5": "76200",
            "askp6": "76300",
            "askp7": "76400",
            "askp8": "76500",
            "askp9": "76600",
            "askp10": "76700",
            "bidp1": "75700",
            "bidp2": "75600",
            "bidp3": "75500",
            "bidp4": "75400",
            "bidp5": "75300",
            "bidp6": "75200",
            "bidp7": "75100",
            "bidp8": "75000",
            "bidp9": "74900",
            "bidp10": "74800",
            "askp_rsqn1": "41846",
            "askp_rsqn2": "12531",
            "askp_rsqn3": "10503",
            "askp_rsqn4": "178397",
            "askp_rsqn5": "50195",
            "askp_rsqn6": "30873",
            "askp_rsqn7": "50728",
            "askp_rsqn8": "69934",
            "askp_rsqn9": "108354",
            "askp_rsqn10": "35543",
            "bidp_rsqn1": "312258",
            "bidp_rsqn2": "347570",
            "bidp_rsqn3": "379261",
            "bidp_rsqn4": "122962",
            "bidp_rsqn5": "108556",
            "bidp_rsqn6": "73542",
            "bidp_rsqn7": "121337",
            "bidp_rsqn8": "382195",
            "bidp_rsqn9": "59117",
            "bidp_rsqn10": "60022",
            "askp_rsqn_icdc1": "0",
            "askp_rsqn_icdc2": "0",
            "askp_rsqn_icdc3": "0",
            "askp_rsqn_icdc4": "0",
            "askp_rsqn_icdc5": "0",
            "askp_rsqn_icdc6": "0",
            "askp_rsqn_icdc7": "0",
            "askp_rsqn_icdc8": "0",
            "askp_rsqn_icdc9": "0",
            "askp_rsqn_icdc10": "0",
            "bidp_rsqn_icdc1": "0",
            "bidp_rsqn_icdc2": "0",
            "bidp_rsqn_icdc3": "0",
            "bidp_rsqn_icdc4": "0",
            "bidp_rsqn_icdc5": "0",
            "bidp_rsqn_icdc6": "0",
            "bidp_rsqn_icdc7": "0",
            "bidp_rsqn_icdc8": "0",
            "bidp_rsqn_icdc9": "0",
            "bidp_rsqn_icdc10": "0",
            "total_askp_rsqn": "588904",
            "total_bidp_rsqn": "1966820",
            "total_askp_rsqn_icdc": "0",
            "total_bidp_rsqn_icdc": "0",
            "ovtm_total_askp_icdc": "0",
            "ovtm_total_bidp_icdc": "0",
            "ovtm_total_askp_rsqn": "0",
            "ovtm_total_bidp_rsqn": "27606",
            "ntby_aspr_rsqn": "1377916",
            "new_mkop_cls_code": "31",
        },
        "output2": {
            "antc_mkop_cls_code": "112",
            "stck_prpr": "75700",
            "stck_oprc": "76100",
            "stck_hgpr": "76600",
            "stck_lwpr": "75600",
            "stck_sdpr": "77300",
            "antc_cnpr": "75700",
            "antc_cntg_vrss_sign": "5",
            "antc_cntg_vrss": "-1600",
            "antc_cntg_prdy_ctrt": "-2.07",
            "antc_vol": "1000673",
            "stck_shrn_iscd": "005930",
            "vi_cls_code": "N",
        },
        "rt_cd": "0",
        "msg_cd": "MCA00000",
        "msg1": "정상처리 되었습니다.",
    }
    assert resp["rt_cd"] == "0"
    assert resp["output2"]["antc_mkop_cls_code"] in ("311", "112")
