name: Build coverage report and Send Codacy

on:
  workflow_dispatch:
    inputs:
      python-version:
        type: choice
        description: 'Python version'
        required: true
        default: '3.11'
        options:
        - '3.9'
        - '3.10'
        - '3.11'
jobs:
  build:
    strategy:
      matrix:
        poetry-version: [ "1.8.2" ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      name: Set up Python ${{ inputs.python-version }}
      with:
        python-version: ${{ inputs.python-version }}
    - uses: abatilo/actions-poetry@v2
      name: Run image
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - name: Install dependencies
      run: |
        poetry install
        poetry run playwright install --with-deps chromium
    - name: Build coverage report
      run: |
        poetry run coverage run -m pytest tests/mocked tests/test_dart_scrap.py
        # poetry run coverage report
        poetry run coverage xml
      env:
        OPENDART_API_KEY: ${{ secrets.OPENDART_API_KEY }}
    - name: Send report to codacy
      run: |
        bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
